// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return android; // Fallback for web
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.linux:
      case TargetPlatform.windows:
        return android; // Fallback for desktop
      default:
        return android; // Absolute fallback
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCENsbYfVRSFFz3B8P2tg95kLJxo4tT26k',
    appId: '1:178528250283:android:2508e51e3dae0441928aee',
    messagingSenderId: '178528250283',
    projectId: 'notefire-623d9',
    storageBucket: 'notefire-623d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALAflkQ7P6ddXVyTr3RxKyTjvYmMz0iZ0',
    appId: '1:178528250283:ios:b5ef39dc9ef8f513928aee',
    messagingSenderId: '178528250283',
    projectId: 'notefire-623d9',
    storageBucket: 'notefire-623d9.firebasestorage.app',
    iosBundleId: 'com.karthickcharanh.firebaseNote',
  );
}
